import React, { useState } from 'react';
import { Habit } from '../types';
import { COLOR_PALETTE } from '../constants';
import { useHabit } from '../contexts/HabitContext';

interface CreateHabitModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

const CreateHabitModal: React.FC<CreateHabitModalProps> = ({ isOpen, onClose }) => {
  const { addHabit } = useHabit();
  const [name, setName] = useState('');
  const [frequency, setFrequency] = useState<'daily' | 'weekly'>('daily');
  const [daysOfWeek, setDaysOfWeek] = useState<number[]>([]);
  const [color, setColor] = useState(COLOR_PALETTE[5]);

  const handleDayToggle = (dayIndex: number) => {
    setDaysOfWeek(prev => 
      prev.includes(dayIndex) 
        ? prev.filter(d => d !== dayIndex)
        : [...prev, dayIndex]
    );
  };
  
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;

    // The ID will be generated by the context/backend.
    const newHabit: Omit<Habit, 'id'> = {
      name: name.trim(),
      frequency,
      daysOfWeek: frequency === 'weekly' ? daysOfWeek.sort() : undefined,
      color,
      completions: {},
      createdAt: new Date().toISOString().split('T')[0],
    };
    addHabit(newHabit);
    // Reset form
    setName('');
    setFrequency('daily');
    setDaysOfWeek([]);
    setColor(COLOR_PALETTE[5]);
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-primary md:bg-black md:bg-opacity-70 flex items-center justify-center z-50">
      <div className="bg-secondary md:rounded-lg shadow-xl p-6 md:p-8 w-full h-full md:h-auto md:max-w-md transform transition-all flex flex-col">
        <div className="flex justify-between items-start mb-6">
          <h2 className="text-2xl font-bold text-text-primary">Create a New Habit</h2>
          <button onClick={onClose} className="text-text-secondary text-3xl hover:text-text-primary">&times;</button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6 flex-grow flex flex-col">
          <div className="flex-grow space-y-6 overflow-y-auto">
            <div>
              <label htmlFor="habitName" className="block text-sm font-medium text-text-secondary">Habit Name</label>
              <input
                id="habitName"
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g., Drink 8 glasses of water"
                className="mt-1 block w-full bg-highlight border border-border-color rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-accent focus:border-accent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-text-secondary">Frequency</label>
              <div className="mt-2 flex space-x-2 bg-highlight p-1 rounded-lg">
                <button type="button" onClick={() => setFrequency('daily')} className={`flex-1 py-1 rounded-md text-sm ${frequency === 'daily' ? 'bg-accent text-white' : 'hover:bg-gray-700'}`}>Daily</button>
                <button type="button" onClick={() => setFrequency('weekly')} className={`flex-1 py-1 rounded-md text-sm ${frequency === 'weekly' ? 'bg-accent text-white' : 'hover:bg-gray-700'}`}>Weekly</button>
              </div>
            </div>

            {frequency === 'weekly' && (
              <div>
                <label className="block text-sm font-medium text-text-secondary">On these days</label>
                <div className="mt-2 grid grid-cols-7 gap-2">
                  {WEEKDAYS.map((day, index) => (
                    <button 
                      key={day}
                      type="button"
                      onClick={() => handleDayToggle(index)}
                      className={`p-2 rounded-md text-sm text-center border transition-colors ${daysOfWeek.includes(index) ? 'bg-accent text-white border-accent' : 'bg-highlight border-border-color hover:border-gray-500'}`}
                    >
                      {day}
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div>
              <label className="block text-sm font-medium text-text-secondary">Color</label>
              <div className="mt-2 grid grid-cols-7 sm:grid-cols-9 gap-2">
                  {COLOR_PALETTE.map(c => (
                      <button
                          key={c}
                          type="button"
                          onClick={() => setColor(c)}
                          className={`w-full pt-[100%] relative rounded-full ${c} ${color === c ? 'ring-2 ring-offset-2 ring-offset-secondary ring-white' : ''}`}
                          aria-label={`Set color to ${c.split('-')[1]}`}
                      ></button>
                  ))}
              </div>
            </div>
          </div>
          
          <div className="mt-8 flex flex-col-reverse md:flex-row justify-end md:space-x-4 gap-2">
            <button type="submit" disabled={!name.trim()} className="px-4 py-3 md:py-2 rounded-md text-white bg-accent hover:bg-blue-500 disabled:opacity-50 w-full md:w-auto">
              Create Habit
            </button>
            <button type="button" onClick={onClose} className="px-4 py-3 md:py-2 rounded-md text-text-primary bg-highlight hover:bg-gray-700 w-full md:w-auto">Cancel</button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateHabitModal;